services:
  flask_app:
    build: .
    ports:
      - "5000:5000"  # mapuje port 5000 ve Flask kontejneru na port 5002 vašeho počítače
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=mypassword
    depends_on:
      - neo4j

  neo4j:
    image: neo4j
    environment:
      - NEO4J_AUTH=neo4j/mypassword
    ports:
      - "7474:7474"
      - "7687:7687"